### PR TITLE
Feat/general cleanup

### PR DESCRIPTION
**Pull request by staeke**
I took the time to fix
- linting
- npm auditing
- engine compatibility (we were already requiring node >6.4.0)
- a bug in printing "manual restart"

### CODE REVIEW

**Comment by staeke** [comment]
ping @whitecolor

**Comment by capaj** [comment]
nice work @staeke. Looks much nicer!

**Comment by capaj** [comment]
@staeke maybe it would make sense to publish your fork namespaced so that I can use it as my daily driver at @leaplabs.
Would you be so kind and publish it?

**Comment by staeke** [comment]
@capaj sorry for the late note....yeah since there's no reply from @whitecolor I'll fork and publish

**Comment by staeke** [comment]
@capaj Reached out to Alex without reply. I sent him another e-mail so we'll see what happens. Meanwhile I merged everything in to my fork here, so you should be able to npm install with

```
npm install git+https://git@github.com/staeke/ts-node-dev.git#1.1.0-staeke
```

**Comment by whitecolor** [comment]
conflicts?

**Comment by staeke** [comment]
@whitecolor fixed

**Pull request closed without merging**
