### PR TITLE
Feat/various fixes

### LINKED ISSUE #92: Debugger detach/notifications for uncaught errors/notification levels
I'm creating this issue to make a pull request. I have the following issues that I've fixed in my fork: 

- ts-node-dev doesn't detach correctly from Chrome's debugger
- No notification for uncaught process errors
- No level on notifications (I prefer errors only)

### PR DESCRIPTION
**Pull request by staeke**
Fixes #92 

- ts-node-dev doesn't detach correctly from Chrome's debugger
- No notification for uncaught process errors
- No level on notifications (I prefer errors only)
- Allow files to not exist that we establish a dependency on (uses chokidar)

Feel free to have opinions on implementation. Maybe there should be on option around the SIGTERM -> SIGINT

Also, I went with sending the notification from `child-require-hook`. Maybe it's cleaner to send something on IPC, and then notification. Any such comments - feel free to comment, and I'll fix

Also, as these are really 4 independent fixes, I could split them if preferred

### CODE REVIEW

**Comment by staeke** [comment]
ping @whitecolor , pls review

**Comment by whitecolor** [comment]
It would be better to split what possible, pls.

**Comment by staeke** [comment]
@whitecolor sorry, missed your comment - will do

**Comment by staeke** [comment]
Separated out to other PRs so closing this

**Pull request closed without merging**
